### ISSUE TITLE
同一md文档中使用navCard导航卡片多次时，数据渲染会叠加出现到其他类

### ISSUE THREAD

**Issue by JalinLei** [Kele-Bingtang/vitepress-theme-teek#71]
## 导航 Navigation

::: navCard 4

```yaml
- name: 链接1
  desc: 链接1

- name: 链接2
  desc: 链接2
```

## 设计 Design

::: navCard 4

```yaml
- name: 链接3
  desc: 链接3
```

:::

链接3会渲染到导航类去
